name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache virtual environment
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: |
            .venv
            ~/.cache/pip
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('gateway/requirements.txt') }}

      - name: Install dependencies
        run: |
          if [ ! -d ".venv" ]; then
            python -m venv .venv
          fi
          .venv/bin/pip install --upgrade pip
          .venv/bin/pip install -r gateway/requirements.txt

      - name: Run tests
        run: |
          PYTHONPATH=. .venv/bin/pytest gateway/tests
